<?php
/**
  * This is the file called by the api url.
  * 
  * This PHP require the autoload.php previously generated by composer
  * Evoque API\Base\ManageAPI Class
  *
  *@package API
  *@filesource
  */
require __DIR__ . '/../../vendor/autoload.php';

use API\Base\ManageAPI;

$api = new ManageAPI($_GET);
echo json_encode($api->GetResponse());
?>